# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Computer Vision Research Group (CVRG)
description: > # this means to ignore newlines until "timezone:"
 Group targets to conduct research on the cutting-edge topics of computer vision related research areas.
timezone: Europe/Istanbul
excerpt_separator: "<!-- excerpt -->"

# Social Media
email:  cvrg@iyte.edu.tr
#twitter_username: 
#instagram_username: 
github_username: cvrg-iyte
#linkedin_id: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/blog/page:num"

collections:
  research:
    output: true
    permalink: /:title
  spotlights:
    output: false
  tags:
    output: true
    permalink: /blog/tags/:title

defaults:
  - scope:
      type: "research"
    values:
      layout: "research"
  - scope:
      type: "posts"
    values:
      permalink: /blog/:year/:month/:day/:title
  - scope:
      type: "spotlights"
    values:
      cover-image: http://placehold.it/750x450
      position: "Member"
  - scope:
      type: "tags"
    values:
      layout: "tag"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - README.md
  - .travis.yml
  - .gitignore
  - LICENSE
  - todo.md
  - old_template_files
